[book]
title = "tytanic"
description = "A guide and reference document for tytanic."
authors = ["tingerrr <tinger@tinger.dev>"]
language = "en"
multilingual = false
src = "src"

[build]
build-dir = "build"

[output.html]
git-repository-url = "https://github.com/typst-community/tytanic"
